pipeline {
    agent any

    tools {
        jdk 'JAVA_HOME'
        maven 'M2_HOME'
    }

    environment {
        DB_URL = 'jdbc:mysql://localhost:3306/microservice_ressource'  
        DB_USER = 'root'  
        DB_PASSWORD = 'root'  
        sonarHostUrl = 'http://192.168.33.10:9000'
        SONAR_TOKEN = 'sqa_f7d516031e481dcda3292b278c1a8d39c1011b36'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'YosrBenAmor-4Twin1-G2', url: 'https://github.com/MeryemBoukraa/4TWIN1-G2-kaddem.git'
            }
        }

        stage('Start MySQL Container') {
            steps {
                script {
                    sh '''
                        docker run --name mysql-test -e MYSQL_ROOT_PASSWORD=root \
                        -e MYSQL_DATABASE=microservice_ressource -p 3306:3306 -d mysql:5.7
                        sleep 20
                    '''
                }
            }
        }

        stage('Compile Projects') {
            steps {
                script {
                    def modules = ['Ressource', 'Eureka', 'ApiGetWay - Copie/ApiGetWay']
                    modules.each { module ->
                        dir(module) {
                            sh 'mvn clean compile'
                        }
                    }
                }
            }
        }


        stage('Run All Tests') {
            steps {
                dir('Ressource') {
                    sh 'mvn test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('Ressource') {
                    sh """
                        mvn sonar:sonar \
                        -Dsonar.token=${SONAR_TOKEN} \
                        -Dsonar.host.url=${sonarHostUrl} \
                        -Dsonar.tests=src/test/java
                    """
                }
            }
        }

        stage('Install Artifacts') {
            steps {
                script {
                    def modules = ['Ressource', 'ApiGetWay - Copie/ApiGetWay', 'Eureka']
                    modules.each { module ->
                        dir(module) {
                            sh 'mvn install'
                        }
                    }
                }
            }
        }

        stage('Deploy to Nexus') {
            steps {
                dir('Ressource') {
                    sh 'mvn deploy -Dmaven.test.skip=true'
                }
            }
        }

        stage('Stop MySQL Container') {
            steps {
                sh '''
                    docker stop mysql-test
                    docker rm mysql-test
                '''
            }
        }

        stage('Build Docker Images') {
            steps {
                script {
                    def images = [
                        'Ressource=yosrba/yosrbenamor-g2-kaddem:1.0',
                        'Eureka=yosrba/eureka:1.0',
                        'ApiGetWay - Copie/ApiGetWay=yosrba/apigetway:1.0'
                    ]
                    images.each { entry ->
                        def (dirName, imageName) = entry.tokenize('=')
                        dir(dirName) {
                            sh "docker build -t ${imageName} ."
                        }
                    }
                }
            }
        }

        stage('Push Docker Images') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                    sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                }

                script {
                    def images = [
                        'yosrba/yosrbenamor-g2-kaddem:1.0',
                        'yosrba/apigetway:1.0',
                        'yosrba/eureka:1.0'
                    ]
                    images.each { img ->
                        sh "docker push ${img}"
                    }
                }
            }
        }

        stage('Start with Docker Compose') {
            steps {
                sh 'docker compose up -d'
            }
        }

        stage('Start Prometheus') {
            steps {
                sh 'docker start prometheus'
            }
        }

        stage('Start Grafana') {
            steps {
                sh 'docker start grafana'
            }
        }
    }

    // post {
    //     always {
    //         sh 'docker-compose down'
    //     }
    // }
}
