version: '3.9'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservice_ressource
    ports:
      - "3306:3306"

  eureka:
    build:
      context: C:/Users/Yosr/OneDrive - ESPRIT/Bureau/Kaddem-DevOps
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - mynetwork

  ressource:
    build: ./devops_back
    image: yosrba/yosrbenamor-g2-kaddem:1.0
    container_name: ressource
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
      spring.datasource.url: "jdbc:mysql://mysql:3306/microservice_ressource?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&max_allowed_packet=15728640"
      spring.datasource.username: "root"
      spring.datasource.password: "root"

  api-gateway:
    build: ./ApiGetWay
    image: yosrba/apigetway:1.0
    container_name: apigetway
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
      - ressource
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"

networks:
  mynetwork:
    driver: bridge
