# Application name
spring.application.name=formation

# Eureka client configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Database configuration
spring.datasource.url=jdbc:mysql://192.168.174.129:3306/timesheet-devops-db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate configuration
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Logging configuration
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot=DEBUG
logging.level.org.springframework.http.converter.json=DEBUG
logging.level.org.springframework=DEBUG

# Server configuration
server.port=8089
server.servlet.context-path=/formation

# Spring Actuator endpoints
management.endpoint.health.enabled=true
management.endpoints.web.exposure.include=health
